COMBO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
CAPS_WORD_ENABLE = yes
FORCE_NKRO = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes